profile=video

gpu-api=vulkan
cursor-autohide=100
sub-bold=yes

screenshot-format=png
screenshot-dir=~/Pictures/mpv

[video]
fullscreen=yes
keep-open=yes
video-sync=display-resample
profile=high-quality
interpolation
save-position-on-quit

[file]
volume=75
loop=inf
